"""Multi-turn trajectory arcs for the text->regex SFT task.

An ARC is the shape of a conversation: turn 1 establishes a pattern, then each
later turn applies a MOVE that transforms it. The move sequence is what varies
between arcs -- if every trajectory were "do a thing, then constrain it", the
model would learn that template rather than the underlying skill.

MOVES
    NARROW      add a constraint that excludes false positives
    BROADEN     relax to admit cases that were wrongly rejected
    REPAIR      bug report citing a concrete failing string
    RETARGET    same skill applied to a different field
    FLAG        requires discovering re.M / re.I / re.S
    PIVOT       change family (validate <-> extract <-> substitute)
    ROLLBACK    return to an earlier turn's answer, plus a change
    COMPOSE     handle an extra case via alternation
    INVERT      match what the previous pattern rejected
    GENERALIZE  parameterise (any N, not just 3)

DISTRIBUTION
Each move appears exactly 6 times across 60 move slots (30 arcs x 2 moves), so
per-move analysis has equal statistical power. This is deliberately NOT the
natural frequency -- in real use "make it stricter" dominates. Uniformity buys
resolution for the question "which conversational moves does SFT improve?",
at the cost of realism. State that trade rather than implying uniform is free.

ROLLBACK appears only in turn-3 slots: it means "revert to an earlier answer
plus a change", and at turn 2 the only earlier answer is turn 1, so reverting
would be a no-op. Its 6 slots therefore all sit in position B, and the other
nine moves absorb the imbalance (4/2 or 3/3 across the two positions).

Turn N's answer must be derivable from turn N-1's *answer alone*, because the
Thinking model's chat template strips <think> blocks from history.
"""

# Pool/held convention matches concepts.py:
#   validate   -> {"positives": [...], "negatives": [...]}
#   extract    -> [[text, expected_or_None], ...]
#   substitute -> [[text, expected_output], ...]

ARCS = [
    # ============================================================ PIVOT -> *
    {
        "concept": "comma_decimal_chain", "arc": "PIVOT->NARROW",
        "turns": [
            {"family": "extract", "traps": ["locate before transform"],
             "instruction": "Capture the first number that uses a comma as its decimal point.",
             "pool": [["Prices: 1,50 and 2,75 EUR", "1,50"], ["weight 10,5 kg", "10,5"], ["no decimals here 42", None]],
             "held": [["a 0,99 b 12,00 c", "0,99"], ["3,141592 approx", "3,141592"]],
             "gold": {"pattern": r"(\d+,\d+)", "flags": ""}},
            {"family": "substitute", "traps": ["restructure into capture groups"],
             "instruction": "Ok great, rewrite that to replace the commas with dots.",
             "pool": [["Prices: 1,50 and 2,75 EUR", "Prices: 1.50 and 2.75 EUR"], ["weight 10,5 kg", "weight 10.5 kg"]],
             "held": [["3,141592 approx", "3.141592 approx"], ["a 0,99 b 12,00 c", "a 0.99 b 12.00 c"]],
             "gold": {"pattern": r"(\d+),(\d+)", "replacement": r"\1.\2", "flags": ""}},
            {"family": "substitute", "traps": ["negative lookahead", "narrow a previous answer"],
             "instruction": "Careful -- some of those are thousands separators. Only convert when there are exactly one or two digits after the comma.",
             "pool": [["Total 1,234,567 items at 2,75 each", "Total 1,234,567 items at 2.75 each"], ["10,5 kg", "10.5 kg"]],
             "held": [["3,141592 approx", "3,141592 approx"], ["mixed 1,234 and 5,67", "mixed 1,234 and 5.67"]],
             "gold": {"pattern": r"(\d+),(\d{1,2})(?!\d)", "replacement": r"\1.\2", "flags": ""}},
        ]},
    {
        "concept": "card_mask_chain", "arc": "PIVOT->ROLLBACK",
        "turns": [
            {"family": "extract", "traps": ["fixed-width counting"],
             "instruction": "Capture the last four digits of a sixteen-digit card number.",
             "pool": [["4111111111111234", "1234"], ["0000111122223333", "3333"]],
             "held": [["9876543210987654", "7654"], ["1111222233334444", "4444"]],
             "gold": {"pattern": r"\d{12}(\d{4})", "flags": ""}},
            {"family": "substitute", "traps": ["lookahead instead of consuming"],
             "instruction": "Now mask everything except those last four digits.",
             "pool": [["4111111111111234", "************1234"], ["1234", "1234"]],
             "held": [["12345", "*2345"], ["0000111122223333", "************3333"]],
             "gold": {"pattern": r"\d(?=\d{4})", "replacement": "*", "flags": ""}},
            {"family": "extract", "traps": ["revert to turn 1's task", "capture the leading group"],
             "instruction": "Drop the masking -- go back to just capturing from a sixteen-digit number, but give me the FIRST four digits instead of the last.",
             "pool": [["4111111111111234", "4111"], ["0000111122223333", "0000"]],
             "held": [["9876543210987654", "9876"], ["short 1234", None]],
             "gold": {"pattern": r"(\d{4})\d{12}", "flags": ""}},
        ]},
    {
        "concept": "phone_chain", "arc": "PIVOT->BROADEN",
        "turns": [
            {"family": "validate", "traps": ["exact length"],
             "instruction": "Match a bare ten-digit phone number with no separators.",
             "pool": {"positives": ["5551234567", "0000000000"], "negatives": ["555123456", "55512345678"]},
             "held": {"positives": ["9998887777"], "negatives": ["555-123-4567", ""]},
             "gold": {"pattern": r"\d{10}", "flags": ""}},
            {"family": "substitute", "traps": ["group reordering", "word boundaries"],
             "instruction": "Now insert hyphens so 5551234567 becomes 555-123-4567.",
             "pool": [["call 5551234567 now", "call 555-123-4567 now"], ["1234567890", "123-456-7890"]],
             "held": [["a 9998887777 b", "a 999-888-7777 b"], ["55512345", "55512345"]],
             "gold": {"pattern": r"\b(\d{3})(\d{3})(\d{4})\b", "replacement": r"\1-\2-\3", "flags": ""}},
            {"family": "substitute", "traps": ["optional group in the replacement"],
             "instruction": "Some numbers carry a +1 country code. Keep the +1 where present and still format the rest as 555-123-4567.",
             "pool": [["+15551234567", "+1555-123-4567"], ["5551234567", "555-123-4567"]],
             "held": [["call +19998887777 now", "call +1999-888-7777 now"], ["nothing", "nothing"]],
             "gold": {"pattern": r"(\+1)?(\d{3})(\d{3})(\d{4})", "replacement": r"\1\2-\3-\4", "flags": ""}},
        ]},
    {
        "concept": "us_date_chain", "arc": "PIVOT->RETARGET",
        "turns": [
            {"family": "validate", "traps": ["month range", "day range"],
             "instruction": "Match a US date MM/DD/YYYY where the month is 01-12 and the day is 01-31, all zero-padded.",
             "pool": {"positives": ["01/15/2024", "12/31/1999"], "negatives": ["13/01/2024", "1/15/2024"]},
             "held": {"positives": ["08/19/2026"], "negatives": ["01/32/2024", "00/10/2024"]},
             "gold": {"pattern": r"(?:0[1-9]|1[0-2])/(?:0[1-9]|[12]\d|3[01])/\d{4}", "flags": ""}},
            {"family": "substitute", "traps": ["group reordering"],
             "instruction": "Now convert those dates into ISO form YYYY-MM-DD.",
             "pool": [["due 01/15/2024 sharp", "due 2024-01-15 sharp"], ["12/31/1999", "1999-12-31"]],
             "held": [["03/04/2020 and 05/06/2021", "2020-03-04 and 2021-05-06"], ["no dates", "no dates"]],
             "gold": {"pattern": r"(\d{2})/(\d{2})/(\d{4})", "replacement": r"\3-\1-\2", "flags": ""}},
            {"family": "substitute", "traps": ["different field order"],
             "instruction": "These logs are European, so the input is actually DD/MM/YYYY. Convert those to ISO YYYY-MM-DD instead.",
             "pool": [["due 15/01/2024 sharp", "due 2024-01-15 sharp"], ["31/12/1999", "1999-12-31"]],
             "held": [["04/03/2020 and 06/05/2021", "2020-03-04 and 2021-05-06"], ["no dates", "no dates"]],
             "gold": {"pattern": r"(\d{2})/(\d{2})/(\d{4})", "replacement": r"\3-\2-\1", "flags": ""}},
        ]},
    # ============================================================ BROADEN -> *
    {
        "concept": "semver_chain", "arc": "BROADEN->REPAIR",
        "turns": [
            {"family": "validate", "traps": ["component count"],
             "instruction": "Match a version number with exactly three dot-separated numeric components and nothing else.",
             "pool": {"positives": ["1.2.3", "0.0.1", "10.20.30"], "negatives": ["1.2", "1.2.3.4"]},
             "held": {"positives": ["99.0.12"], "negatives": ["v1.2.3", "abc"]},
             "gold": {"pattern": r"\d+\.\d+\.\d+", "flags": ""}},
            {"family": "validate", "traps": ["optional suffix"],
             "instruction": "Now also allow an optional pre-release suffix: a hyphen followed by one or more letters, digits, dots or hyphens.",
             "pool": {"positives": ["1.2.3", "1.0.0-beta.1", "2.3.4-rc1"], "negatives": ["1.2", "1.2.3-"]},
             "held": {"positives": ["1.0.0-alpha.beta.2"], "negatives": ["1.2.3.4", "-1.2.3"]},
             "gold": {"pattern": r"\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?", "flags": ""}},
            {"family": "validate", "traps": ["leading-zero rejection", "fix a cited failure"],
             "instruction": "Bug: it accepted '01.2.3', but our registry rejects leading zeros in any numeric component. A component that is just '0' is still fine. Fix that.",
             "pool": {"positives": ["1.2.3", "0.0.1", "1.0.0-beta.1"], "negatives": ["01.2.3", "1.2.03"]},
             "held": {"positives": ["10.20.30"], "negatives": ["1.02.3", "00.1.2"]},
             "gold": {"pattern": r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?", "flags": ""}},
        ]},
    {
        "concept": "hex_color_chain", "arc": "BROADEN->ROLLBACK",
        "turns": [
            {"family": "validate", "traps": ["two valid lengths"],
             "instruction": "Match a CSS hex colour: '#' then exactly three or exactly six hex digits, in either case.",
             "pool": {"positives": ["#fff", "#FFFFFF", "#a1b2c3"], "negatives": ["#ffff", "#gg0000"]},
             "held": {"positives": ["#000"], "negatives": ["fff", "#12345"]},
             "gold": {"pattern": r"#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})", "flags": ""}},
            {"family": "validate", "traps": ["four valid lengths", "alpha channel"],
             "instruction": "Also allow the alpha forms: four or eight hex digits as well.",
             "pool": {"positives": ["#fff", "#ffff", "#ffffffff"], "negatives": ["#fffff", "#gg0000"]},
             "held": {"positives": ["#a1b2c3d4"], "negatives": ["#f", "#1234567"]},
             "gold": {"pattern": r"#(?:[0-9A-Fa-f]{3,4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})", "flags": ""}},
            {"family": "validate", "traps": ["revert to turn 1's rule", "restrict the alphabet to lower case"],
             "instruction": "Scrap the alpha forms -- go back to the original three-or-six-digit rule, but now accept lowercase hex digits only.",
             "pool": {"positives": ["#fff", "#a1b2c3"], "negatives": ["#FFF", "#ffff"]},
             "held": {"positives": ["#000000"], "negatives": ["#A1B2C3", "#ffffffff"]},
             "gold": {"pattern": r"#(?:[0-9a-f]{3}|[0-9a-f]{6})", "flags": ""}},
        ]},
    {
        "concept": "time_chain", "arc": "BROADEN->INVERT",
        "turns": [
            {"family": "validate", "traps": ["hour range", "minute range"],
             "instruction": "Match a 24-hour time HH:MM with hours 00-23 and minutes 00-59, zero-padded.",
             "pool": {"positives": ["00:00", "23:59", "09:30"], "negatives": ["24:00", "12:60"]},
             "held": {"positives": ["19:45"], "negatives": ["9:30", "23:5"]},
             "gold": {"pattern": r"(?:[01]\d|2[0-3]):[0-5]\d", "flags": ""}},
            {"family": "validate", "traps": ["optional seconds group"],
             "instruction": "Allow optional seconds too, as :SS with seconds 00-59.",
             "pool": {"positives": ["00:00", "23:59:59", "09:30:00"], "negatives": ["24:00", "12:30:60"]},
             "held": {"positives": ["19:45:01"], "negatives": ["12:30:", "12:30:1"]},
             "gold": {"pattern": r"(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?", "flags": ""}},
            {"family": "validate", "traps": ["match the complement of the hour range"],
             "instruction": "Now flip it: match strings of the HH:MM shape that the hour rule REJECTS -- two digits, a colon, then minutes 00-59, where the hour is 24 or greater.",
             "pool": {"positives": ["24:00", "99:59"], "negatives": ["23:59", "00:00"]},
             "held": {"positives": ["30:15", "45:00"], "negatives": ["12:60", "9:30"]},
             "gold": {"pattern": r"(?:2[4-9]|[3-9]\d):[0-5]\d", "flags": ""}},
        ]},
    # ============================================================ NARROW -> *
    {
        "concept": "log_level_chain", "arc": "NARROW->COMPOSE",
        "turns": [
            {"family": "extract", "traps": ["alternation of literals"],
             "instruction": "Capture the log level from a line. Levels are DEBUG, INFO, WARN, ERROR or FATAL.",
             "pool": [["2024-01-01 INFO started", "INFO"], ["2024-01-01 ERROR failed", "ERROR"], ["no level here", None]],
             "held": [["x DEBUG y", "DEBUG"], ["a FATAL b", "FATAL"]],
             "gold": {"pattern": r"\b(DEBUG|INFO|WARN|ERROR|FATAL)\b", "flags": ""}},
            {"family": "extract", "traps": ["restrict the alternation"],
             "instruction": "I only care about serious ones. Capture the level only when it is ERROR or FATAL.",
             "pool": [["2024-01-01 ERROR failed", "ERROR"], ["2024-01-01 INFO started", None]],
             "held": [["a FATAL b", "FATAL"], ["x DEBUG y", None]],
             "gold": {"pattern": r"\b(ERROR|FATAL)\b", "flags": ""}},
            {"family": "extract", "traps": ["add a case to the alternation"],
             "instruction": "Add WARN to that set as well -- WARN, ERROR or FATAL.",
             "pool": [["a WARN b", "WARN"], ["a ERROR b", "ERROR"], ["a INFO b", None]],
             "held": [["a FATAL b", "FATAL"], ["a DEBUG b", None]],
             "gold": {"pattern": r"\b(WARN|ERROR|FATAL)\b", "flags": ""}},
        ]},
    {
        "concept": "port_chain", "arc": "NARROW->ROLLBACK",
        "turns": [
            {"family": "validate", "traps": ["upper bound 65535", "no leading zeros"],
             "instruction": "Match a TCP port: an integer 0 to 65535 with no leading zeros.",
             "pool": {"positives": ["0", "80", "8080", "65535"], "negatives": ["65536", "99999"]},
             "held": {"positives": ["443"], "negatives": ["070", "-1"]},
             "gold": {"pattern": r"(?:6553[0-5]|655[0-2]\d|65[0-4]\d\d|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3}|0)", "flags": ""}},
            {"family": "validate", "traps": ["narrow to 1-1023", "boundary at 1023"],
             "instruction": "Only privileged ports now: 1 through 1023 inclusive, still with no leading zeros.",
             "pool": {"positives": ["1", "80", "1023"], "negatives": ["0", "1024"]},
             "held": {"positives": ["999", "443"], "negatives": ["65535", "01"]},
             "gold": {"pattern": r"(?:10(?:[01]\d|2[0-3])|[1-9]\d{0,2})", "flags": ""}},
            {"family": "validate", "traps": ["revert to the full range", "exclude a single boundary value"],
             "instruction": "Go back to the full port range from turn one, but exclude 0 -- port 0 is not assignable.",
             "pool": {"positives": ["1", "8080", "65535"], "negatives": ["0", "65536"]},
             "held": {"positives": ["1023", "1024"], "negatives": ["070", "99999"]},
             "gold": {"pattern": r"(?:6553[0-5]|655[0-2]\d|65[0-4]\d\d|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3})", "flags": ""}},
        ]},
    {
        "concept": "email_domain_chain", "arc": "NARROW->FLAG",
        "turns": [
            {"family": "validate", "traps": ["no whitespace or @ in parts"],
             "instruction": "Match a simple email address: non-space non-@ characters, an @, more such characters, a dot, then more.",
             "pool": {"positives": ["a@b.co", "bob@example.com"], "negatives": ["a@b", "no-at.com"]},
             "held": {"positives": ["x.y@sub.d.org"], "negatives": ["a b@c.co", "@b.co"]},
             "gold": {"pattern": r"[^\s@]+@[^\s@]+\.[^\s@]+", "flags": ""}},
            {"family": "validate", "traps": ["fixed literal domain", "escaping the dot"],
             "instruction": "Restrict it to our company: the domain must be exactly example.com.",
             "pool": {"positives": ["bob@example.com", "a.b@example.com"], "negatives": ["bob@other.com", "bob@example.org"]},
             "held": {"positives": ["x@example.com"], "negatives": ["bob@sub.example.com", "bob@exampleXcom"]},
             "gold": {"pattern": r"[^\s@]+@example\.com", "flags": ""}},
            {"family": "validate", "traps": ["IGNORECASE flag", "case-insensitive domain only"],
             "instruction": "Our mail gateway uppercases domains, so bob@EXAMPLE.COM arrives too. Accept the domain in any letter case.",
             "pool": {"positives": ["bob@example.com", "bob@EXAMPLE.COM"], "negatives": ["bob@other.com", "bob@example.org"]},
             "held": {"positives": ["a@Example.Com"], "negatives": ["bob@EXAMPLEXCOM", "@EXAMPLE.COM"]},
             "gold": {"pattern": r"[^\s@]+@example\.com", "flags": "i"}},
        ]},
    # ============================================================ REPAIR -> *
    {
        "concept": "whitespace_chain", "arc": "REPAIR->FLAG",
        "turns": [
            {"family": "substitute", "traps": ["whitespace class"],
             "instruction": "Collapse every run of whitespace into a single space.",
             "pool": [["a   b", "a b"], ["x\t\ty", "x y"], ["p  q  r", "p q r"]],
             "held": [["one\ntwo", "one two"], ["  lead  ", " lead "]],
             "gold": {"pattern": r"\s+", "replacement": " ", "flags": ""}},
            {"family": "substitute", "traps": ["exclude newline from the class", "fix a cited failure"],
             "instruction": "Bug: on 'a   b\\nc   d' it flattened my line breaks into spaces. Keep newlines intact and only collapse spaces and tabs.",
             "pool": [["a   b\nc   d", "a b\nc d"], ["x\t\ty\nz", "x y\nz"]],
             "held": [["one\n\ntwo", "one\n\ntwo"], ["p  q", "p q"]],
             "gold": {"pattern": r"[ \t]+", "replacement": " ", "flags": ""}},
            {"family": "substitute", "traps": ["MULTILINE flag", "end-of-line anchoring"],
             "instruction": "Different job now: remove spaces and tabs only where they sit at the end of a line, leaving inner spacing alone.",
             "pool": [["a   b   \nc\n", "a   b\nc\n"], ["one  \ntwo\t\n", "one\ntwo\n"]],
             "held": [["  keep  \n", "  keep\n"], ["clean\n", "clean\n"]],
             "gold": {"pattern": r"[ \t]+$", "replacement": "", "flags": "m"}},
        ]},
    {
        "concept": "csv_chain", "arc": "REPAIR->GENERALIZE",
        "turns": [
            {"family": "substitute", "traps": ["MULTILINE anchoring", "field must not contain the delimiter"],
             "instruction": "Swap the two comma-separated fields on every line, so 'a,b' becomes 'b,a'. Fields never contain commas.",
             "pool": [["first,second", "second,first"], ["a,b\nc,d", "b,a\nd,c"]],
             "held": [["1,2\n3,4", "2,1\n4,3"], ["nocomma", "nocomma"]],
             "gold": {"pattern": r"^([^,\n]+),([^,\n]+)$", "replacement": r"\2,\1", "flags": "m"}},
            {"family": "substitute", "traps": ["three fields", "fix a cited failure"],
             "instruction": "Bug: it left 'a,b,c' completely untouched. These rows have three columns -- reverse all three, so 'a,b,c' becomes 'c,b,a'.",
             "pool": [["a,b,c", "c,b,a"], ["1,2,3\n4,5,6", "3,2,1\n6,5,4"]],
             "held": [["x,y,z", "z,y,x"], ["only,two", "only,two"]],
             "gold": {"pattern": r"^([^,\n]+),([^,\n]+),([^,\n]+)$", "replacement": r"\3,\2,\1", "flags": "m"}},
            {"family": "substitute", "traps": ["drop the end anchor to admit any field count"],
             "instruction": "The column count varies row to row. Generalise it: swap just the first two fields of every line, however many fields follow.",
             "pool": [["a,b,c", "b,a,c"], ["first,second", "second,first"]],
             "held": [["1,2,3,4\n5,6", "2,1,3,4\n6,5"], ["nocomma", "nocomma"]],
             "gold": {"pattern": r"^([^,\n]+),([^,\n]+)", "replacement": r"\2,\1", "flags": "m"}},
        ]},
    {
        "concept": "comment_chain", "arc": "REPAIR->ROLLBACK",
        "turns": [
            {"family": "substitute", "traps": ["end-of-line anchoring", "eat preceding spaces"],
             "instruction": "Remove trailing '#' comments and any spaces immediately before them, keeping the line break.",
             "pool": [["x = 1  # set x", "x = 1"], ["y = 2 # note\nz = 3", "y = 2\nz = 3"]],
             "held": [["a = 1#c\nb = 2", "a = 1\nb = 2"], ["no comment", "no comment"]],
             "gold": {"pattern": r"[ \t]*#[^\n]*", "replacement": "", "flags": ""}},
            {"family": "substitute", "traps": ["whole-line only", "consume the newline", "fix a cited failure"],
             "instruction": "Bug: on '# header\\nx = 1' it left an empty first line behind. Only delete lines that are entirely a comment, taking their line break with them.",
             "pool": [["# header\nx = 1\n", "x = 1\n"], ["a = 1\n# mid\nb = 2\n", "a = 1\nb = 2\n"]],
             "held": [["  # indented\nb = 2\n", "b = 2\n"], ["x = 1  # keep\n", "x = 1  # keep\n"]],
             "gold": {"pattern": r"^[ \t]*#[^\n]*\n?", "replacement": "", "flags": "m"}},
            {"family": "substitute", "traps": ["revert to trailing-comment stripping", "negative lookahead on a shebang"],
             "instruction": "Go back to the turn-one behaviour of stripping trailing comments, but leave a shebang '#!' untouched.",
             "pool": [["x = 1  # note", "x = 1"], ["#!/bin/sh\ny = 2", "#!/bin/sh\ny = 2"]],
             "held": [["#!/usr/bin/env python\nz = 3  # c", "#!/usr/bin/env python\nz = 3"], ["plain", "plain"]],
             "gold": {"pattern": r"[ \t]*#(?!!)[^\n]*", "replacement": "", "flags": ""}},
        ]},
    # ============================================================ RETARGET -> *
    {
        "concept": "url_chain", "arc": "RETARGET->PIVOT",
        "turns": [
            {"family": "extract", "traps": ["optional www", "stop at the path"],
             "instruction": "Capture the host of the first http or https URL, excluding any leading www. and excluding the path.",
             "pool": [["visit https://www.example.com/page", "example.com"], ["http://sub.a.org/x", "sub.a.org"], ["no url", None]],
             "held": [["https://example.com", "example.com"], ["https://www.a.co.uk/", "a.co.uk"]],
             "gold": {"pattern": r"https?://(?:www\.)?([^/\s?]+)", "flags": ""}},
            {"family": "extract", "traps": ["capture a different field", "path may be just a slash"],
             "instruction": "Now capture the path instead -- everything from the first slash after the host up to any query string.",
             "pool": [["https://www.example.com/page", "/page"], ["http://a.org/x/y?z=1", "/x/y"]],
             "held": [["https://example.com/", "/"], ["https://a.com/deep/path/here", "/deep/path/here"]],
             "gold": {"pattern": r"https?://[^/\s?]+(/[^\s?]*)", "flags": ""}},
            {"family": "substitute", "traps": ["escaping dots in a literal host"],
             "instruction": "Now rewrite URLs to point at our mirror: replace the host old.example.com with mirror.example.net, keeping scheme and path.",
             "pool": [["https://old.example.com/a", "https://mirror.example.net/a"], ["http://old.example.com", "http://mirror.example.net"]],
             "held": [["https://other.com/a", "https://other.com/a"], ["see https://old.example.com/x/y now", "see https://mirror.example.net/x/y now"]],
             "gold": {"pattern": r"old\.example\.com", "replacement": "mirror.example.net", "flags": ""}},
        ]},
    {
        "concept": "ssn_chain", "arc": "RETARGET->NARROW",
        "turns": [
            {"family": "substitute", "traps": ["preserve the last group"],
             "instruction": "Redact SSNs of the form NNN-NN-NNNN, replacing the first two groups with asterisks and keeping the last four digits.",
             "pool": [["ssn 123-45-6789 on file", "ssn ***-**-6789 on file"], ["000-00-0000", "***-**-0000"]],
             "held": [["a 111-22-3333 b", "a ***-**-3333 b"], ["no ssn", "no ssn"]],
             "gold": {"pattern": r"\d{3}-\d{2}-(\d{4})", "replacement": r"***-**-\1", "flags": ""}},
            {"family": "substitute", "traps": ["unseparated form", "word boundaries"],
             "instruction": "Some records store SSNs as nine digits with no hyphens. Redact those instead, keeping the last four: 123456789 becomes *****6789.",
             "pool": [["ssn 123456789 ok", "ssn *****6789 ok"], ["000000000", "*****0000"]],
             "held": [["a 111223333 b", "a *****3333 b"], ["12345", "12345"]],
             "gold": {"pattern": r"\b\d{5}(\d{4})\b", "replacement": r"*****\1", "flags": ""}},
            {"family": "substitute", "traps": ["require a preceding label", "lookbehind"],
             "instruction": "Too aggressive -- it hit phone numbers. Only redact when the digits are directly preceded by the label 'SSN: '.",
             "pool": [["SSN: 123456789", "SSN: *****6789"], ["Phone: 5551234567", "Phone: 5551234567"]],
             "held": [["SSN: 000000000 and 987654321", "SSN: *****0000 and 987654321"], ["no label 111223333", "no label 111223333"]],
             "gold": {"pattern": r"(?<=SSN: )\d{5}(\d{4})\b", "replacement": r"*****\1", "flags": ""}},
        ]},
    {
        "concept": "markdown_chain", "arc": "RETARGET->FLAG",
        "turns": [
            {"family": "substitute", "traps": ["anchor to the very start of the text"],
             "instruction": "The text begins with a Markdown level-1 header. Convert that leading '# ' line into <h1>text</h1>. Only the header at the very start of the text should change.",
             "pool": [["# Title", "<h1>Title</h1>"], ["# Top\nbody", "<h1>Top</h1>\nbody"]],
             "held": [["body\n# Later", "body\n# Later"], ["no header", "no header"]],
             "gold": {"pattern": r"^# (.+)", "replacement": r"<h1>\1</h1>", "flags": ""}},
            {"family": "substitute", "traps": ["different header level"],
             "instruction": "Do level-2 headers instead: a leading '## ' line becomes <h2>text</h2>, still only at the very start of the text.",
             "pool": [["## Sub", "<h2>Sub</h2>"], ["## Top\nbody", "<h2>Top</h2>\nbody"]],
             "held": [["# One\n## Two", "# One\n## Two"], ["plain", "plain"]],
             "gold": {"pattern": r"^## (.+)", "replacement": r"<h2>\1</h2>", "flags": ""}},
            {"family": "substitute", "traps": ["MULTILINE flag", "apply to every line"],
             "instruction": "Apply that to every level-2 header in the document, not just one at the start.",
             "pool": [["## A\n## B", "<h2>A</h2>\n<h2>B</h2>"], ["intro\n## Sub\n", "intro\n<h2>Sub</h2>\n"]],
             "held": [["# One\n## Two\n", "# One\n<h2>Two</h2>\n"], ["### Deep\n", "### Deep\n"]],
             "gold": {"pattern": r"^## (.+)$", "replacement": r"<h2>\1</h2>", "flags": "m"}},
        ]},
    {
        "concept": "acronym_chain", "arc": "RETARGET->COMPOSE",
        "turns": [
            {"family": "extract", "traps": ["minimum length two", "word boundaries"],
             "instruction": "Capture the first all-uppercase acronym of two or more letters.",
             "pool": [["the NASA mission", "NASA"], ["using an API today", "API"], ["all lowercase", None]],
             "held": [["XML and JSON", "XML"], ["a single then HTTP", "HTTP"]],
             "gold": {"pattern": r"\b([A-Z]{2,})\b", "flags": ""}},
            {"family": "extract", "traps": ["switch to the opposite case class"],
             "instruction": "Different field: capture the first all-lowercase word of four or more letters instead.",
             "pool": [["the NASA mission", "mission"], ["API and json here", "json"], ["ALL CAPS ONLY", None]],
             "held": [["a bb ccc dddd", "dddd"], ["HTTP works well", "works"]],
             "gold": {"pattern": r"\b([a-z]{4,})\b", "flags": ""}},
            {"family": "extract", "traps": ["alternation over two classes"],
             "instruction": "Capture whichever comes first: an all-uppercase acronym of two or more letters, or an all-lowercase word of four or more letters.",
             # 'the' is only 3 lowercase letters, so NASA is genuinely first here.
             "pool": [["the NASA mission", "NASA"], ["mission for NASA", "mission"], ["a bb NASA", "NASA"]],
             "held": [["xyz ABC", "ABC"], ["hello world", "hello"]],
             "gold": {"pattern": r"\b([A-Z]{2,}|[a-z]{4,})\b", "flags": ""}},
        ]},
    # ============================================================ FLAG -> *
    {
        "concept": "trailing_ws_chain", "arc": "FLAG->PIVOT",
        "turns": [
            {"family": "substitute", "traps": ["end-of-string anchoring only"],
             "instruction": "Remove spaces and tabs at the very end of the text. Trailing whitespace on earlier lines should be left alone.",
             "pool": [["hello   ", "hello"], ["a  \nb  ", "a  \nb"]],
             "held": [["x\t\t", "x"], ["clean", "clean"]],
             "gold": {"pattern": r"[ \t]+$", "replacement": "", "flags": ""}},
            {"family": "substitute", "traps": ["MULTILINE flag", "every line not just the last"],
             "instruction": "Now do that at the end of every line, not just the end of the text.",
             "pool": [["a  \nb  ", "a\nb"], ["one \ntwo\t\n", "one\ntwo\n"]],
             "held": [["  keep  \n", "  keep\n"], ["clean\n", "clean\n"]],
             "gold": {"pattern": r"[ \t]+$", "replacement": "", "flags": "m"}},
            {"family": "extract", "traps": ["switch to capturing", "lazy quantifier before the anchor"],
             "instruction": "Stop rewriting. Capture the text of the first line with its trailing spaces and tabs excluded.",
             "pool": [["a   \nb\n", "a"], ["hello  ", "hello"]],
             "held": [["  keep  \nx", "  keep"], ["clean\n", "clean"]],
             "gold": {"pattern": r"^([^\n]*?)[ \t]*$", "flags": "m"}},
        ]},
    {
        "concept": "ini_value_chain", "arc": "FLAG->BROADEN",
        "turns": [
            {"family": "extract", "traps": ["whitespace around the equals", "single-line only"],
             "instruction": "The text is a single config line. Capture the value assigned to the key 'timeout', ignoring spaces around the equals sign.",
             "pool": [["timeout = 30", "30"], ["timeout=60", "60"], ["host=localhost", None]],
             "held": [["timeout   =   90", "90"], ["timeout = ", ""]],
             "gold": {"pattern": r"^timeout[ \t]*=[ \t]*(.*)$", "flags": ""}},
            {"family": "extract", "traps": ["MULTILINE flag", "key may be on any line"],
             "instruction": "Real config files have many lines. Find the timeout key wherever it appears in the file.",
             "pool": [["host=localhost\ntimeout=60", "60"], ["timeout = 30\nother = 1", "30"]],
             "held": [["[sec]\nport = 1\ntimeout = 5", "5"], ["host=x\nport=1", None]],
             "gold": {"pattern": r"^timeout[ \t]*=[ \t]*(.*)$", "flags": "m"}},
            {"family": "extract", "traps": ["IGNORECASE flag", "combine two flags"],
             "instruction": "Some files capitalise the key. Match it whatever the letter case -- TIMEOUT, Timeout and timeout should all work.",
             "pool": [["TIMEOUT = 30", "30"], ["host=x\nTimeout=60", "60"]],
             "held": [["[s]\ntimeout = 5", "5"], ["TIMEOUTS = 9", None]],
             "gold": {"pattern": r"^timeout[ \t]*=[ \t]*(.*)$", "flags": "mi"}},
        ]},
    {
        "concept": "blank_line_chain", "arc": "FLAG->ROLLBACK",
        "turns": [
            {"family": "substitute", "traps": ["quantifier lower bound"],
             "instruction": "Collapse runs of three or more newlines into exactly two, leaving single and double breaks alone.",
             "pool": [["a\n\n\nb", "a\n\nb"], ["a\n\n\n\n\nb", "a\n\nb"]],
             "held": [["a\n\nb", "a\n\nb"], ["x\n\n\n\ny\n\n\nz", "x\n\ny\n\nz"]],
             "gold": {"pattern": r"\n{3,}", "replacement": "\n\n", "flags": ""}},
            {"family": "substitute", "traps": ["MULTILINE anchoring", "whitespace-only lines"],
             "instruction": "Different job: delete any line that contains only spaces or tabs, including its line break.",
             "pool": [["a\n   \nb\n", "a\nb\n"], ["x\n\t\ny\n", "x\ny\n"]],
             "held": [["a\nb\n", "a\nb\n"], ["p\n \n \nq\n", "p\nq\n"]],
             "gold": {"pattern": r"^[ \t]*\n", "replacement": "", "flags": "m"}},
            {"family": "substitute", "traps": ["revert to newline collapsing", "tighten the lower bound"],
             "instruction": "Go back to collapsing newline runs like turn one, but this time collapse any run of two or more newlines down to a single newline.",
             "pool": [["a\n\nb", "a\nb"], ["a\n\n\n\nb", "a\nb"]],
             "held": [["a\nb", "a\nb"], ["x\n\ny\n\n\nz", "x\ny\nz"]],
             "gold": {"pattern": r"\n{2,}", "replacement": "\n", "flags": ""}},
        ]},
    # ============================================================ COMPOSE -> *
    {
        "concept": "password_chain", "arc": "COMPOSE->BROADEN",
        "turns": [
            {"family": "validate", "traps": ["three lookaheads", "minimum length"],
             "instruction": "Match a password of at least 8 characters containing at least one lowercase letter, one uppercase letter and one digit. Letters and digits only.",
             "pool": {"positives": ["Passw0rd", "aA1aaaaa"], "negatives": ["password", "Passw0r"]},
             "held": {"positives": ["abcDEF12"], "negatives": ["PASSWORD1", "aA1aaaa"]},
             "gold": {"pattern": r"(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{8,}", "flags": ""}},
            {"family": "validate", "traps": ["fourth lookahead", "extend the allowed alphabet"],
             "instruction": "Now also require at least one special character from @$!%*?& and allow those characters in the password.",
             "pool": {"positives": ["Passw0rd!", "aA1@aaaa"], "negatives": ["Passw0rd", "aA1@aaa"]},
             "held": {"positives": ["Str0ng@Pass"], "negatives": ["Passw0rd!#", "PASSW0RD!"]},
             "gold": {"pattern": r"(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}", "flags": ""}},
            {"family": "validate", "traps": ["lower the length bound"],
             "instruction": "Users are complaining. Drop the minimum length to 6, keeping every other requirement.",
             "pool": {"positives": ["aA1@aa", "Passw0rd!"], "negatives": ["aA1@a", "aA1aaa"]},
             "held": {"positives": ["Xy9$zz"], "negatives": ["aaaaaa", "AA1@AA"]},
             "gold": {"pattern": r"(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,}", "flags": ""}},
        ]},
    {
        "concept": "currency_chain", "arc": "COMPOSE->NARROW",
        "turns": [
            {"family": "validate", "traps": ["thousands separators", "optional decimals"],
             "instruction": "Match a US dollar amount: '$', then digits optionally grouped with commas in threes, optionally then a dot and exactly two decimals.",
             "pool": {"positives": ["$5", "$1,000", "$1,234.56"], "negatives": ["5", "$1.234"]},
             "held": {"positives": ["$0.99"], "negatives": ["$1,00", "$"]},
             "gold": {"pattern": r"\$\d{1,3}(?:,\d{3})*(?:\.\d{2})?|\$\d+(?:\.\d{2})?", "flags": ""}},
            {"family": "validate", "traps": ["alternation of symbols"],
             "instruction": "We now bill in euros too. Accept a leading euro sign as well as a dollar sign.",
             "pool": {"positives": ["$5", "€1,234.56", "€0.99"], "negatives": ["5", "£5"]},
             "held": {"positives": ["$1,000"], "negatives": ["€1.234", "€"]},
             "gold": {"pattern": r"[$€](?:\d{1,3}(?:,\d{3})*(?:\.\d{2})?|\d+(?:\.\d{2})?)", "flags": ""}},
            {"family": "validate", "traps": ["make the decimal part mandatory"],
             "instruction": "The ledger requires cents. Now the decimal part is mandatory -- exactly two digits after a dot, always.",
             "pool": {"positives": ["$1,234.56", "€0.99"], "negatives": ["$5", "€1,000"]},
             "held": {"positives": ["$12.00"], "negatives": ["$1.234", "€1,234"]},
             "gold": {"pattern": r"[$€](?:\d{1,3}(?:,\d{3})*|\d+)\.\d{2}", "flags": ""}},
        ]},
    {
        "concept": "slug_chain", "arc": "COMPOSE->INVERT",
        "turns": [
            {"family": "validate", "traps": ["no leading or trailing separator", "no repeated separators"],
             "instruction": "Match a URL slug: lowercase letters and digits in groups separated by single hyphens, with no leading, trailing or repeated hyphens.",
             "pool": {"positives": ["hello-world", "abc123", "a-b-c"], "negatives": ["-leading", "a--b"]},
             "held": {"positives": ["my-post-123"], "negatives": ["trailing-", "Hello"]},
             "gold": {"pattern": r"[a-z0-9]+(?:-[a-z0-9]+)*", "flags": ""}},
            {"family": "validate", "traps": ["add a second separator to the class"],
             "instruction": "Our CMS also emits underscores as separators. Accept underscore as well as hyphen, under the same rules.",
             "pool": {"positives": ["hello_world", "a-b_c", "abc123"], "negatives": ["_leading", "a__b"]},
             "held": {"positives": ["my_post-123"], "negatives": ["trailing_", "a-_b"]},
             "gold": {"pattern": r"[a-z0-9]+(?:[-_][a-z0-9]+)*", "flags": ""}},
            {"family": "validate", "traps": ["match the complement of a character class"],
             "instruction": "Flip it into a linter: match any string that contains at least one character outside the allowed set of lowercase letters, digits, hyphen and underscore.",
             "pool": {"positives": ["Hello", "has space"], "negatives": ["hello-world", "abc_123"]},
             "held": {"positives": ["café", "a!b"], "negatives": ["", "a-b_c"]},
             "gold": {"pattern": r"[\s\S]*[^a-z0-9_-][\s\S]*", "flags": ""}},
        ]},
    # ============================================================ INVERT -> *
    {
        "concept": "identifier_chain", "arc": "INVERT->REPAIR",
        "turns": [
            {"family": "validate", "traps": ["first-character class differs from the rest"],
             "instruction": "Match a Python identifier: starts with a letter or underscore, then any number of letters, digits or underscores.",
             "pool": {"positives": ["foo", "_bar", "a1"], "negatives": ["1foo", "foo-bar"]},
             "held": {"positives": ["__init__"], "negatives": ["9lives", "foo bar"]},
             "gold": {"pattern": r"[A-Za-z_][A-Za-z0-9_]*", "flags": ""}},
            {"family": "validate", "traps": ["match the rejected leading-digit case"],
             "instruction": "Now match the opposite: strings made of identifier characters that are invalid precisely because they begin with a digit.",
             "pool": {"positives": ["1foo", "9lives"], "negatives": ["foo", "_bar"]},
             "held": {"positives": ["0x", "42a"], "negatives": ["a1", "foo-bar"]},
             "gold": {"pattern": r"\d[A-Za-z0-9_]*", "flags": ""}},
            {"family": "validate", "traps": ["require a letter or underscore somewhere", "fix a cited failure"],
             "instruction": "Bug: it matched '99', but a bare run of digits is a number, not a malformed identifier. Require at least one letter or underscore somewhere after the leading digit.",
             "pool": {"positives": ["1foo", "9lives"], "negatives": ["99", "foo"]},
             "held": {"positives": ["0x", "42a"], "negatives": ["123456", "_bar"]},
             "gold": {"pattern": r"\d[A-Za-z0-9_]*[A-Za-z_][A-Za-z0-9_]*", "flags": ""}},
        ]},
    {
        "concept": "hex_literal_chain", "arc": "INVERT->RETARGET",
        "turns": [
            {"family": "validate", "traps": ["prefix required", "hex alphabet"],
             "instruction": "Match a hexadecimal literal: '0x' or '0X' followed by one or more hexadecimal digits.",
             "pool": {"positives": ["0xff", "0XFF", "0x0"], "negatives": ["ff", "0x"]},
             "held": {"positives": ["0xDEADBEEF"], "negatives": ["0xg1", "x0ff"]},
             "gold": {"pattern": r"0[xX][0-9A-Fa-f]+", "flags": ""}},
            {"family": "validate", "traps": ["match the rejected invalid-digit case"],
             "instruction": "Now match the malformed ones instead: a '0x' prefix followed by alphanumerics where at least one character is a letter outside the hex range a-f.",
             "pool": {"positives": ["0xg1", "0xZZ"], "negatives": ["0xff", "0x0"]},
             "held": {"positives": ["0X1g2"], "negatives": ["0xDEADBEEF", "0x"]},
             "gold": {"pattern": r"0[xX][0-9A-Za-z]*[g-zG-Z][0-9A-Za-z]*", "flags": ""}},
            {"family": "validate", "traps": ["different literal prefix", "different invalid alphabet"],
             "instruction": "Same idea for binary literals: a '0b' prefix followed by digits where at least one digit is 2 through 9.",
             "pool": {"positives": ["0b102", "0B19"], "negatives": ["0b101", "0b0"]},
             "held": {"positives": ["0b1112"], "negatives": ["0b1010", "0b"]},
             "gold": {"pattern": r"0[bB][0-9]*[2-9][0-9]*", "flags": ""}},
        ]},
    {
        "concept": "us_zip_chain", "arc": "INVERT->GENERALIZE",
        "turns": [
            {"family": "validate", "traps": ["exact length"],
             "instruction": "Match a US ZIP code: exactly five digits and nothing else.",
             "pool": {"positives": ["12345", "00000"], "negatives": ["1234", "123456"]},
             "held": {"positives": ["90210"], "negatives": ["abcde", "1234a"]},
             "gold": {"pattern": r"\d{5}", "flags": ""}},
            {"family": "validate", "traps": ["match the rejected lengths"],
             "instruction": "Now match the digit strings that rule rejects on length: all-digit strings that are one to four digits, or six or more.",
             "pool": {"positives": ["1234", "123456"], "negatives": ["12345", "abcde"]},
             "held": {"positives": ["1", "1234567890"], "negatives": ["00000", "1234a"]},
             "gold": {"pattern": r"\d{1,4}|\d{6,}", "flags": ""}},
            {"family": "validate", "traps": ["parameterise the length bound"],
             "instruction": "We are going international. Generalise the original rule to a postal code of any length from four to ten digits.",
             "pool": {"positives": ["1234", "12345", "1234567890"], "negatives": ["123", "12345678901"]},
             "held": {"positives": ["123456"], "negatives": ["abcde", "1234a"]},
             "gold": {"pattern": r"\d{4,10}", "flags": ""}},
        ]},
    # ============================================================ GENERALIZE -> *
    {
        "concept": "md_header_chain", "arc": "GENERALIZE->COMPOSE",
        "turns": [
            {"family": "substitute", "traps": ["MULTILINE anchoring"],
             "instruction": "Convert Markdown level-1 headers to HTML: a line starting '# ' becomes <h1>text</h1>.",
             "pool": [["# Title", "<h1>Title</h1>"], ["# A\n# B", "<h1>A</h1>\n<h1>B</h1>"]],
             "held": [["## Sub", "## Sub"], ["not a header", "not a header"]],
             "gold": {"pattern": r"^# (.+)$", "replacement": r"<h1>\1</h1>", "flags": "m"}},
            {"family": "substitute", "traps": ["parameterise the repeat count"],
             "instruction": "Handle any header level from one to six hashes, emitting a generic <h>text</h> tag regardless of depth.",
             "pool": [["# A\n### C", "<h>A</h>\n<h>C</h>"], ["###### Deep", "<h>Deep</h>"]],
             "held": [["####### TooDeep", "####### TooDeep"], ["plain", "plain"]],
             "gold": {"pattern": r"^#{1,6} (.+)$", "replacement": r"<h>\1</h>", "flags": "m"}},
            {"family": "substitute", "traps": ["alternation of two marker syntaxes"],
             "instruction": "This document also uses a run of '=' characters as a header marker on the same line. Treat those the same way.",
             "pool": [["# A\n=== B", "<h>A</h>\n<h>B</h>"], ["= C", "<h>C</h>"]],
             "held": [["## D\n== E", "<h>D</h>\n<h>E</h>"], ["plain", "plain"]],
             "gold": {"pattern": r"^(?:#{1,6}|=+) (.+)$", "replacement": r"<h>\1</h>", "flags": "m"}},
        ]},
    {
        "concept": "quoted_chain", "arc": "GENERALIZE->REPAIR",
        "turns": [
            {"family": "extract", "traps": ["greedy vs lazy"],
             "instruction": "Capture the contents of the first double-quoted string, without the quotes.",
             "pool": [['he said "hello" then "bye"', "hello"], ['"only"', "only"], ["none here", None]],
             "held": [['"first" "second"', "first"], ['a "x" b', "x"]],
             "gold": {"pattern": r'"([^"]*)"', "flags": ""}},
            {"family": "extract", "traps": ["parameterise the delimiter"],
             "instruction": "Generalise it: the delimiter may be a double quote, a single quote or a backtick. Capture the contents of the first quoted run, whichever delimiter is used.",
             "pool": [["he said 'hello' ok", "hello"], ["use `code` here", "code"], ['a "x" b', "x"]],
             "held": [["none here", None], ["'first' `second`", "first"]],
             "gold": {"pattern": r"[\"'`]([^\"'`]*)[\"'`]", "flags": ""}},
            # Requiring only "non-empty" is not enough: on `"" and 'x'` the engine
            # pairs the 2nd delimiter with the 3rd -- across different delimiter
            # types -- and captures ' and '. Excluding whitespace from the content
            # class rules that out without needing a backreference (which would put
            # the content in group 2 and break the extract contract).
            {"family": "extract", "traps": ["reject cross-delimiter pairing", "fix a cited failure"],
             "instruction": "Bug: on `\"\" and 'x'` it captured ' and ', pairing a quote with a different delimiter type. Require the content to be at least one character long and to contain no whitespace.",
             "pool": [["\"\" and 'x'", "x"], ["`code`", "code"]],
             "held": [["'' `` 'real'", "real"], ["none here", None], ['"hello world"', None]],
             "gold": {"pattern": r"[\"'`]([^\"'`\s]+)[\"'`]", "flags": ""}},
        ]},
    {
        "concept": "repeated_word_chain", "arc": "GENERALIZE->ROLLBACK",
        "turns": [
            {"family": "extract", "traps": ["backreference to a capture group"],
             "instruction": "Capture a word that is immediately repeated, separated by exactly one space. Return the repeated word once.",
             "pool": [["the the cat", "the"], ["a bb bb c", "bb"], ["no repeats here", None]],
             "held": [["say say again", "say"], ["one two three", None]],
             "gold": {"pattern": r"\b(\w+) \1\b", "flags": ""}},
            {"family": "extract", "traps": ["parameterise the separator"],
             "instruction": "Generalise the gap: allow any run of whitespace between the two copies, not just a single space.",
             "pool": [["the   the cat", "the"], ["a bb\tbb c", "bb"]],
             "held": [["say\nsay again", "say"], ["one two three", None]],
             "gold": {"pattern": r"\b(\w+)\s+\1\b", "flags": ""}},
            {"family": "extract", "traps": ["revert the separator rule", "IGNORECASE affects the backreference"],
             "instruction": "Go back to requiring exactly one space, but ignore letter case so 'The the' counts as a repeat.",
             "pool": [["The the cat", "The"], ["a BB bb c", "BB"]],
             "held": [["Say say again", "Say"], ["the   the", None]],
             "gold": {"pattern": r"\b(\w+) \1\b", "flags": "i"}},
        ]},
    {
        "concept": "file_extension_chain", "arc": "GENERALIZE->INVERT",
        "turns": [
            {"family": "extract", "traps": ["last dot not first", "end anchoring"],
             "instruction": "Capture the file extension: the characters after the final dot, excluding the dot. There is no trailing whitespace.",
             "pool": [["report.pdf", "pdf"], ["archive.tar.gz", "gz"], ["noextension", None]],
             "held": [["a.b.c.txt", "txt"], ["path/to/file.py", "py"]],
             "gold": {"pattern": r"\.([^.]+)$", "flags": ""}},
            {"family": "extract", "traps": ["capture a multi-part extension", "first dot of the final segment"],
             "instruction": "Generalise to multi-part extensions: capture everything after the FIRST dot of the final path segment, so archive.tar.gz gives tar.gz.",
             "pool": [["archive.tar.gz", "tar.gz"], ["report.pdf", "pdf"]],
             "held": [["path/to/file.py", "py"], ["a.b.c.txt", "b.c.txt"]],
             "gold": {"pattern": r"[^/.]*\.(.+)$", "flags": ""}},
            {"family": "extract", "traps": ["match names the previous pattern rejected"],
             "instruction": "Flip it: match filenames that have no extension at all, capturing the whole name. There are no path separators in these.",
             "pool": [["noextension", "noextension"], ["report.pdf", None]],
             "held": [["README", "README"], ["archive.tar.gz", None]],
             "gold": {"pattern": r"^([^/.]+)$", "flags": ""}},
        ]},
]
